url: localhost
baseurl: ""

# Site settings
title: Ardhi & Hilda
email: me@ardhipoetra.web.id
description: "who care about description :p"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Build settings
markdown: kramdown
permalink: pretty
google_api_key: AIzaSyAAru0fGb4T6vH8nu4ITrqHOICiw7RKyCU
